version: "3"
services:
  dht:
    container_name: dht
    image: agelosnm/dht:v1
    restart: always
    ports:
      - "5000:5000"
    networks:
      - dht
    depends_on:
      - mongo
    env_file: ./server/.env
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - dht
    volumes:
      - mongo-data:/data/db
networks:
  dht:
    driver: bridge
volumes:
  mongo-data:
    driver: local